# cgroup2 mount opts
#CG_MOUNT_OPTS="nodev,noexec,nosuid"

# This controls if the root cg mount has a named init child
#CG_CHILD=false

# the init child name
#CG_CHILD_NAME=artix

# the extension of the service cg name
#CG_SV_EXT=".sv"

# This variable contains the cgroups version 2 settings for your services.
# If this is set in this file, the settings will apply to all services.
# If you want different settings for each service, place them in the conf
# for service foo.
# The format is to specify the setting and value followed by a newline.
# Multiple settings and values can be specified.
# For example, you would use this to set the maximum memory and maximum
# number of pids for a service.
#SV_CG_SETTINGS="
#memory.max 10485760
#pids.max max
#"
#
# For more information about the adjustments that can be made with
# cgroups version 2, see Documentation/cgroups-v2.txt in the linux kernel
# source tree.
#SV_CG_SETTINGS=""

# If this is yes, we will send sighup to the processes in the cgroup
# immediately after stopsig and sigcont.
#SV_CG_SEND_SIGHUP=false

# This is the amount of time in seconds that we delay after sending sigcont
# and optionally sighup, before we optionally send sigkill to all
# processes in the # cgroup.
# The default is 90 seconds.
#SV_CG_TIMEOUT_STOPSEC="90"

# If this is set to no, we do not send sigkill to all processes in the
# cgroup.
#SV_CG_SEND_SIGKILL=true

